name: Este es mi primer YML
run-name: Aprendiedo YML y github actions
on: 
  push:
    branches:
      - main
      - low      
jobs:
  lint-code:
    runs-on: ubuntu-lastest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: install dependecies
        run: npm run lint